media:
  - name: rank-utah
    label: rank-utah
    input: sites/rank-utah/assets/media
    output: /media
  - name: nova-gutter
    label: nova-gutter
    input: sites/nova-gutter/assets/media
    output: /media

components:
  titleField:
    label: Title
    type: string
    required: true
    description: |
      Include your city or a nearby landmark in your title to drive more local traffic

  dateField:
    label: Date
    type: date
    description: |
      Pick today’s date, or change it if you need to backdate your post.

  statusField:
    label: Status
    type: select
    required: true
    default: Draft
    options:
      values:
        - Draft
        - Published
    description: |
      Leave as “Draft” (default) to keep the post unpublished.
      Select “Published” to make it live, then click Save.

  tagsField:
    label: Tags
    type: select
    options:
      multiple: true
      creatable: true
      placeholder: "Add tags…"
    description: |
      Use as few tags as necessary (lowercase, singular, hyphens for multi-word)
      to help visitors find related content and keep your site organized.

  bodyField:
    label: Body
    type: rich-text
    required: true
    description: |
      Use the `/` command to insert images and headings.
      Highlight text to format or add links.
      After inserting an image, click it, choose ‘ALT,’ and add a short description (e.g. "People watching fireworks in Salt Lake City") to boost accessibility and SEO.
      Organize your content under H2 & H3 subheadings for clear structure (title uses H1 by default).

  startDateField:
    label: Start Date & Time
    type: date
    required: false
    options:
      time: true
      format: yyyy-MM-dd'T'HH:mm
    description: |
      Set the event start date and time. Leave blank if this post is not an event.

  endDateField:
    label: End Date & Time
    type: date
    required: false
    options:
      time: true
      format: yyyy-MM-dd'T'HH:mm
    description: |
      Set the event end date and time. Leave blank if this post is not an event.

  locationNameField:
    label: Venue Name
    type: string
    required: false
    description: |
      Name of the event’s physical venue (e.g. theater, park, conference hall). Leave blank if this post is not an event.

  locationAddressField:
    label: Venue Address
    type: string
    required: false
    description: |
      Full address including street, city, state, ZIP, and country. Example: "123 Main St, Salt Lake City, UT 84101, USA". Leave blank if this post is not an event.

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"

    view:
      fields: [ date, is_published, title, tags ]
      sort:   [ date ]
      default:
        sort:  date
        order: desc

    fields:
      - name: date
        component: dateField
      - name: is_published
        component: statusField
      - name: title
        component: titleField
      - name: tags
        component: tagsField
        options:
          fetch:
            url: https://spotlight.rankutah.com/tags/index.json
            method: GET
            results: ""
      - name: body
        component: bodyField
      - name: startDate
        component: startDateField
      - name: endDate
        component: endDateField
      - name: locationName
        component: locationNameField
      - name: locationAddress
        component: locationAddressField

  # Example: new client setup
  - name: nova-gutter
    label: nova-gutter posts
    type: collection
    path: sites/nova-gutter/content/posts
    filename: "{primary}.md"

    view:
      fields: [ date, is_published, title, tags ]
      sort:   [ date ]
      default:
        sort:  date
        order: desc

    fields:
      - name: date
        component: dateField
      - name: is_published
        component: statusField
      - name: title
        component: titleField
      - name: tags
        component: tagsField
        options:
          fetch:
            url: https://nova-gutter.pages.dev/tags/index.json
            method: GET
            results: ""
      - name: body
        component: bodyField
      - name: startDate
        component: startDateField
      - name: endDate
        component: endDateField
      - name: locationName
        component: locationNameField
      - name: locationAddress
        component: locationAddressField
